### PR TITLE
Bug 1931277 - Support for Configuring a Subset of Interesting Metrics…

### PR DESCRIPTION
**Pull request by mkmelin**
… to Collect.

### CODE REVIEW

**Review by travis79 — COMMENTED** [review]
This is looking great! Would you mind adding some test coverage for this in `tests/test_parser.py` so we can ensure we don't regress this in the future?

**Comment by mkmelin** [comment]
Updated. FWIW, seems the project is missing some deps. This is what I had to do to make it work:

cd ~/Code/github-glean_parser
mkdir /tmp/mm-env
python3 -m venv /tmp/mm-env
source /tmp/mm-env/bin/activate
pip3 install -r requirements_dev.txt
pip3 install diskcache jsonschema platformdirs
export PYTHONPATH=$PYTHONPATH:`pwd`

pytest tests/test_parser.py

**Comment by badboy** [comment]
those deps are part of the package definition, so a `pip install -e .` should install them.

**Comment by mkmelin** [comment]
> those deps are part of the package definition, so a `pip install -e .` should install them.

Ah yes, that worked!

**Comment by mkmelin** [comment]
Resolved the lint task failure, so this should now be ready to merge.

**Pull request merged**
