### PR TITLE
fixes Bug 1682583: glean_parser metrics.md generation inserts some extra blank lines

### PR DESCRIPTION
**Pull request by anuragakella**
### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `make test` runs without emitting any warnings
  - `make lint` runs without emitting any errors
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry to `HISTORY.rst` or an explanation of why it does not need one
  - Any breaking changes to language binding APIs are noted explicitly

### Details  

 This PR is a simple bug fix, so no additional tests are required. No changelog entry in HISTORY.rst too, a bug fix - doesn't change any functionality.
  
running mdl on the generated output files gives these unique errors:
1. MD006 Consider starting bulleted lists at the beginning of the line
2. MD012 Multiple consecutive blank lines 
4. MD013 Line length
5. MD022 Headers should be surrounded by blank lines
6. MD033 Inline HTML
7. MD034 Bare URL used

this PR fixes 1, 2, and 5.
6 - can be ignored: the error snippet is -- The key format is ‘<provider-name>’
the lint tool classifies <provider-name> as a HTML tag.

here's a gist that shows the old and the new files:
[Link to the Gist](<https://gist.github.com/anuragakella/c135d50e7e70d923967277d36e368b06>)

the ones that have to be solved are - 4 and 7
for 4, one solution I can think of is, checking line length and splitting lines if they're too long but that would involve adding exceptions for URLs because splitting URLs would cause problems.
for 7, URLs need to be identified/parsed before writing the generated text to the output file and should be reformatted wth angular brackets: '<URL>'

I need some help here, are those errors ignore-able or am I supposed to fix them? 
If yes, how? what would be a good solution to those errors? 

This is my first contribution to Mozilla / OpenSource in general!
Thank you for your time

### CODE REVIEW

**Review by mdboom — COMMENTED** [review]
Thanks for the pull request, and sorry for the delay in getting back to you.

To make this easier to review, can you update the gist with *exactly* what glean_parser is now outputting?  The markdown seems to be somehow messed with and includes things it seems really unlikely that glean_parser would produce, for example the `<>` around URLs in this snippet:

```
All Glean pings contain built-in metrics in the [`ping_info`](<https://mozilla.github.io/glean/book/user/pings/index.html#the-ping_info-section>) and [`client_info`](<https://mozilla.github.io/glean/book/user/pings/index.html#the-client_info-section>) sections.
```

**Comment by anuragakella** [comment]
> Thanks for the pull request, and sorry for the delay in getting back to you.
> 
> To make this easier to review, can you update the gist with _exactly_ what glean_parser is now outputting? The markdown seems to be somehow messed with and includes things it seems really unlikely that glean_parser would produce, for example the `<>` around URLs in this snippet:
> 
> ```
> All Glean pings contain built-in metrics in the [`ping_info`](<https://mozilla.github.io/glean/book/user/pings/index.html#the-ping_info-section>) and [`client_info`](<https://mozilla.github.io/glean/book/user/pings/index.html#the-client_info-section>) sections.
> ```

Thank you for the reply, 

about the `<>`:
I was trying to manually remove the linter errors by modifying the .md file because the linter seems to have a bug, it was printing incorrect line numbers.

I probably used the manually edited file to make the gist, without realizing it.
Here's the new, corrected gist: [metrics.md](https://gist.github.com/anuragakella/2c90c6d6ee42e0992b2e0781f91cd288)

Apologies for the confusion.

Please do let me know if I need to make changes and/or fix the other mdl errors.

**Comment by mdboom** [comment]
No problem!  Now it looks like the gist is the `yaml` input, not the `md` output.  Would you mind updating again?

**Comment by anuragakella** [comment]
> No problem! Now it looks like the gist is the `yaml` input, not the `md` output. Would you mind updating again?

Oh god, sorry about the stupid mistakes, I was working on something else and pasted that file without checking
[metrics.md](https://gist.github.com/anuragakella/2c90c6d6ee42e0992b2e0781f91cd288)
here ^ 

I'm so sorry

**Review by mdboom — CHANGES_REQUESTED** [review]
No worries.  While this doesn't address all of the markdown nits, it addresses the simple-to-resolve ones and the sources of problems originally reported.

Only one additional request: We don't need to include the metrics.yaml and metrics.md files in the git repository here -- they will remain in the `glean` repo.  If you can just `git rm` them and repush your branch, then I think this is ready to merge.

**Comment by anuragakella** [comment]
> No worries. While this doesn't address all of the markdown nits, it addresses the simple-to-resolve ones and the sources of problems originally reported.
> 
> Only one additional request: We don't need to include the metrics.yaml and metrics.md files in the git repository here -- they will remain in the `glean` repo. If you can just `git rm` them and repush your branch, then I think this is ready to merge.

Done! 

If its needed, I could work on removing the other errors too, but I'd need some help / a few pointers

Thank you!

**Review by mdboom — APPROVED** [review]
Thanks!

**Pull request merged**
