### PR TITLE
Bug 1705671 - Add support for labeled metric types in JS and TS templates

### PR DESCRIPTION
**Pull request by brizental**
### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - `make test` runs without emitting any warnings
  - `make lint` runs without emitting any errors
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
  - Any breaking changes to language binding APIs are noted explicitly

--- 

Example Typescript generated code:

```ts
/* eslint-disable */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser.  DO NOT EDIT.

import LabeledMetricType from "@mozilla/glean/webext/private/metrics/labeled";
import CounterMetricType from "@mozilla/glean/webext/private/metrics/counter";

/**
 * Foo
 *
 * Generated from `category.counter`.
 */
export const counter = new CounterMetricType({
    category: "category",
    name: "counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
});

/**
 * Foo
 *
 * Generated from `category.labeled_counter`.
 */
export const labeledCounter = new LabeledMetricType({
    category: "category",
    name: "labeled_counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
    CounterMetricType,
});
```

Example Javsacript generated code:

```js
/* eslint-disable */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser.  DO NOT EDIT.

import LabeledMetricType from "@mozilla/glean/webext/private/metrics/labeled";
import CounterMetricType from "@mozilla/glean/webext/private/metrics/counter";

"use strict"

/**
 * Foo
 *
 * Generated from `category.counter`.
 */
export const counter = new CounterMetricType({
    category: "category",
    name: "counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
});

/**
 * Foo
 *
 * Generated from `category.labeled_counter`.
 */
export const labeledCounter = new LabeledMetricType({
    category: "category",
    name: "labeled_counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
    CounterMetricType,
});
```

Note: it is the same template. The file extension and the `use strict` stamenet are the only difference.

### CODE REVIEW

**Review by Dexterp37 — COMMENTED** [review]
@brizental would you kindly provide a sample that uses static labels, too?

mh, there's also two other weird things:

- CounterMetricType is inclued after the LabeledType..
- "use strict" is after the imports: shouldn't this be the first directive in the file?

**Comment by brizental** [comment]
> CounterMetricType is inclued after the LabeledType..

This was a choice, but no reason for it. I can switch it to the bottom of the imports, what would be the difference though?

> "use strict" is after the imports: shouldn't this be the first directive in the file?

Good catch, this was true forever is this template... I'll fix it.

**Comment by Dexterp37** [comment]
> 
> 
> > CounterMetricType is inclued after the LabeledType..
> 
> This was a choice, but no reason for it. I can switch it to the bottom of the imports, what would be the difference though?

It shouldn't matter too much, I concur. Labeled imports the other types already, import order shouldn't matter anymore, but I thought we were at least listing imports alphabetically :) No big deal

**Comment by brizental** [comment]
Ok, tehre was a bug in the previous template, we were adding the extra comments inside the metric data object. We should provide a way to test these templates in Javascript/Typescript as well as have the glean_parser tests. WDYT, @Dexterp37 ?

The fixed template in Javascript:

```js
"use strict";

/* eslint-disable */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser.  DO NOT EDIT.

import LabeledMetricType from "@mozilla/glean/webext/private/metrics/labeled";
import CounterMetricType from "@mozilla/glean/webext/private/metrics/counter";


/**
 * Foo
 *
 * Generated from `category.counter`.
 */
export const counter = new CounterMetricType({
    category: "category",
    name: "counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
});

/**
 * Foo
 *
 * Generated from `category.labeled_counter`.
 */
export const labeledCounter = new LabeledMetricType({
    category: "category",
    name: "labeled_counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
}, CounterMetricType, ["_.is_fine", "this-is-fine", "this.is-fine", "this.is.fine", "this.is_still_fine", "this_is_fine_too", "thisisfine"]);
```

The fixed template in Typescript:
```ts
/* eslint-disable */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser.  DO NOT EDIT.

import LabeledMetricType from "@mozilla/glean/webext/private/metrics/labeled";
import CounterMetricType from "@mozilla/glean/webext/private/metrics/counter";


/**
 * Foo
 *
 * Generated from `category.counter`.
 */
export const counter = new CounterMetricType({
    category: "category",
    name: "counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
});

/**
 * Foo
 *
 * Generated from `category.labeled_counter`.
 */
export const labeledCounter = new LabeledMetricType({
    category: "category",
    name: "labeled_counter",
    sendInPings: ["core"],
    lifetime: "user",
    disabled: false,
}, CounterMetricType, ["_.is_fine", "this-is-fine", "this.is-fine", "this.is.fine", "this.is_still_fine", "this_is_fine_too", "thisisfine"]);
```

**Comment by Dexterp37** [comment]
> 
> 
> Ok, there was a bug in the previous template, we were adding the extra comments inside the metric data object. We should provide a way to test these templates in Javascript/Typescript as well as have the glean_parser tests. WDYT, @Dexterp37 ?

That would be a good idea, yes. For a follow-up, though :)

**Review by Dexterp37 — APPROVED** [review]

**Pull request merged**
